### ISSUE TITLE
Request: Docker Image

### ISSUE THREAD

**Issue by adaptive** [memc-rs/memc-rs#3]
Super!
I would prefer to use your official Docker image, instead of building my own. Something similar to [memcache](https://hub.docker.com/_/memcached)

**Comment by DariuszOstolski** [comment]
Hi,

I've just publish docker image under memc-rs repository:
https://hub.docker.com/r/memcrs/memc-rs/tags

You can pull it as usuall:
docker pull memcrs/memc-rs:0.0.1a

BR,
Dariusz

**Comment by adaptive** [comment]
Great @DariuszOstolski!
I will do development testing, then a Canary release and see how it behaves at scale.

**Comment by adaptive** [comment]
@DariuszOstolski so far development testing going well. Can you create a repo for your docker image?

**Comment by adaptive** [comment]
Never mind, I noticed the Dockerfile. I will close this issue now.
